### ISSUE TITLE
ALL CAPS QR codes get prepended with an additonal http:// prefix

### ISSUE THREAD

**Issue by Bubu** [SecUSo/privacy-friendly-qr-scanner#104]
Trying to scan this qr code and opening it leads on an additional `http://` prefix. This can easily be verified by installing the [Intent Intercept](https://f-droid.org/en/packages/de.k3b.android.intentintercept/) app and inspecting the intent sent by secuso qr code scanner.

![image](https://user-images.githubusercontent.com/105185/120891396-c01b8880-c608-11eb-8123-d994e55715d2.png)

**Comment by Kamuno** [comment]
Thanks.. this is a rather annoying bug but should be an easy fix

**Comment by kaiserls** [comment]
@Bubu , @Kamuno : Could one of you explain why this is a bug? What expected behavior is disturbed?


The bug/(feature?) is located in 
https://github.com/SecUSo/privacy-friendly-qr-scanner/blob/fc90aec1f11d4a90460bf17e2f2fc7b29db9ad41/app/src/main/java/com/secuso/privacyFriendlyCodeScanner/qrscanner/generator/QRCodeEncoder.java#L86-L97
and prepends http:// to every web_url, but not URIs. It could be removed by replacing the if else branch with the second statement.

**Comment by Bubu** [comment]
> Could one of you explain why this is a bug? What expected behavior is disturbed?

The above QR code gets opened as `http://HTTPS://BUBU1.EU/<...>` which of course the trips up receivers of this urls. (F-Droid client in this case.)

**Comment by kaiserls** [comment]
I would like to mention that the qr code given by @Bubu  is forwarding my browser to the website described here: https://www.scamdoc.com/view/582732
and therefore I would like to raise some concerns regarding this issue.
@Bubu : Could you explain this?

**Comment by Bubu** [comment]
@kaiserls 

The qr code contains the following text `HTTPS://BUBU1.EU/CCTG/FDROID/REPO?FINGERPRINT=F3F30B6D212D84AEA604C3DF00E9E4D4A39194A33BF6EC58DB53AF0AC4B41BEC`

Note that this url/path doesn't actually exist, only the lowercase alternative does. An F-Droid client will correctly convert it to lowercase and it'll work.

Meanwhile it just returns 404 and any redirection to any scam sites must be happening on your client-side.

```
 curl -v HTTPS://BUBU1.EU/CCTG/FDROID/REPO?FINGERPRINT=F3F30B6D212D84AEA604C3DF00E9E4D4A39194A33BF6EC58DB53AF0AC4B41BEC
*   Trying 176.9.145.28:443...
* Connected to BUBU1.EU (176.9.145.28) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=bubu1.eu
*  start date: Jun 11 21:03:49 2021 GMT
*  expire date: Sep  9 21:03:48 2021 GMT
*  subjectAltName: host "BUBU1.EU" matched cert's "bubu1.eu"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x56190d231970)
> GET /CCTG/FDROID/REPO?FINGERPRINT=F3F30B6D212D84AEA604C3DF00E9E4D4A39194A33BF6EC58DB53AF0AC4B41BEC HTTP/2
> Host: BUBU1.EU
> user-agent: curl/7.77.0
> accept: */*
> accept-encoding: deflate, gzip, zstd
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 404 
< server: nginx/1.21.1
< date: Sun, 11 Jul 2021 15:22:47 GMT
< content-type: text/html; charset=utf-8
< strict-transport-security: max-age=63072000; includeSubDomains; preload
< referrer-policy: strict-origin
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< content-encoding: gzip
< 
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.21.1</center>
</body>
</html>
* Connection #0 to host BUBU1.EU left intact
```

**Comment by Bubu** [comment]
Btw. the whole ALL_CAPS thing for f-droid repos wasn't my idea. I don't know which tools generated this error, I just forwarded a bug report from mastodon that someone couldn't scan the code with this Scanner here where it works correctly when scanned from both Binary Eye and the old Barcode Scanner project.

**Comment by kaiserls** [comment]
@Bubu Thank your for the quick and kind response! :)

#106 works with the fdroid client, but not with the browser. However I don't think that we can fix this due to the case sensitivity of urls:
https://stackoverflow.com/questions/7996919/should-url-be-case-sensitive
