### ISSUE TITLE
Allow the QR-Scanner to open and read images from storage

### ISSUE THREAD

**Issue by NGeek752** [SecUSo/privacy-friendly-qr-scanner#109]
This feature may not be privacy friendly, but there are limited privacy-friendly options out there.
Sometimes the qr code appears on your phone's browser, unable to be scanned, and it could be really frustrating.
It would be a great deed if you include that.
Thanks for your wrok!

**Comment by Kamuno** [comment]
We would not want to include on screen qr code read functionality but allowing the QR-Scanner to open and read images could be a valid option.

I will change the topic of the issue to reflect this suggestion. Thanks for using the qr code scanner :)

**Comment by cbiere** [comment]
https://github.com/wewewe718/QrAndBarcodeScanner implements this feature.
