### ISSUE TITLE
App crashes on scan

### ISSUE THREAD

**Issue by zellchristensen** [SecUSo/privacy-friendly-qr-scanner#115]
Tried scanning some barcodes on coupons in the mail and they crash the app.  Never had an issue with any others.

![2022-01-03_18-34-36](https://user-images.githubusercontent.com/38737447/147994833-bbfd815d-b8e3-40d5-8967-61a8c4170c05.jpg)
![2022-01-03_18-34-57](https://user-images.githubusercontent.com/38737447/147994836-7a087155-9577-450b-8d43-0ddb7a742b65.jpg)
![2022-01-03_18-34-49](https://user-images.githubusercontent.com/38737447/147994838-64331277-94fd-46c6-9c8b-976aa549ec2d.jpg)

**Comment by Kamuno** [comment]
Thanks for the report. The fix will be published in the next release.
