### ISSUE TITLE
Please provide an option to disable the web search (e.g. a "None" option in search engine choice)

### ISSUE THREAD

**Issue by ZornsLemma** [SecUSo/privacy-friendly-qr-scanner#116]
The app works well, but if I'm scanning something confidential I don't want to be one accidental screen tap away from sharing the results with a search engine. If you could offer "None" in the search engine list along with Google and DuckDuckGo and get rid of the "Proceed" button to do the web search if "None" is selected that would be great.

**Comment by Kamuno** [comment]
I did not add a "none" option but added a confirmation dialog, updated the button description and added a dedicated option to turn off the button entirely. I would consider this issue fixed with this change.

**Comment by ZornsLemma** [comment]
Thanks, that sounds better than adding a "None" option anyway. I will give this a try when it's on F-Droid, thanks very much for looking at this!
