### ISSUE TITLE
Problem faced when adding to contact into phone from a vCard or meCard.

### ISSUE THREAD

**Issue by Pagi-Maula** [SecUSo/privacy-friendly-qr-scanner#119]
Whenever I scan a meCard or vCard and click on proceed and tap on add to contact it does nothing. Please look into the issue.

**Comment by enricotagliavini** [comment]
Same for me on OnePlus nord. The original Barcode Scanner from the ZXing Projekt works and uses the contact app correctly.

**Comment by Kamuno** [comment]
We will update this in a upcoming release.. however, we could not reproduce the issue directly. So we don't know if our change fixed it. We will probably release the update next week. Maybe you could test this on your devices again with the new update? :) 

Thanks for reporting

**Comment by enricotagliavini** [comment]
Ehy sorry for the very late answer, I just want to confirm the issue seems to be fixed, thank you so much!
