### ISSUE TITLE
Scanning local images?

### ISSUE THREAD

**Issue by Freeplayg** [SecUSo/privacy-friendly-qr-scanner#128]
Would be very helpful, sometimes people send me QR codes through messages and I can't... scan them with my own phone

Would be even better possibly adding the option to "share" the image to the app, to scan the code

**Comment by Kamuno** [comment]
both already implemented in v4.0.0 :) this was released a few days ago. I will close this issue for now. Reopen it if you find bugs with the feature :)

**Comment by Freeplayg** [comment]
Oh! I'm sorry I didn't realize. I downloaded the app through F-Droid which was updated 5 months ago...

**Comment by Kamuno** [comment]
F-Droid didnt pull the update yet. It should be available there soon :)
