### ISSUE TITLE
Ability to add to quick settings menu

### ISSUE THREAD

**Issue by KorneevVitaly** [SecUSo/privacy-friendly-qr-scanner#138]
It would be nice to have ability to add app icon to swipe down menu for quick access if this possible:

![Screenshot_2022-08-07-20-38-52-161_com miui home](https://user-images.githubusercontent.com/47393025/183303922-c9f976b0-6981-4e2e-9132-943c87b37159.jpg)
![Screenshot_2022-08-07-20-38-42-188_com miui home](https://user-images.githubusercontent.com/47393025/183303927-c5996f9e-d245-41cd-bf28-7a033d06882e.jpg)

**Comment by udenr** [comment]
This functionality was added in #132 and is included in the current 4.2.0 release.
