### ISSUE TITLE
Support for more languages

### ISSUE THREAD

**Issue by moayad-star** [SecUSo/privacy-friendly-qr-scanner#156]
There is no option in the settings to convert between languages

If you add more languages, the application will be more likely to spread, and I will help you translate the application into Arabic

Let me know if you like it, I'll be happy to contribute with you

**Comment by jamoness** [comment]
Yes, we need more languages, simply because not everyone speaks English. I offer my help to translate it into Spanish.

**Comment by Alexandre7627** [comment]
I offer my help to translate it into French !
