### ISSUE TITLE
Android camera encountered a problem

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-qr-scanner#16]
I cannot use the scanner on my CyanogenMod device. Restarting the device does not solve the issue.

![photo_2016-12-22_00-04-38](https://cloud.githubusercontent.com/assets/7099812/21407853/4b1ed0f4-c7da-11e6-9143-d847dabb7691.jpg)

CM: 13.0
Android: 6.0.1

**Comment by Drezil** [comment]
Same for me.
Fresh install oft cm today, app worked.
After installing opengapps pico i startend encountering this issue.

Maybe that helps.

**Comment by Yonjuni** [comment]
@Drezil Interesting ;-) Thanks for the comment. I don't use GAPPS on the device with the issue. 
Which CM version do you have?

**Comment by tobiasneidig** [comment]
Same here on my Nexus 5 with Google Android 6.0.1. All other camera or qr scanner apps are working as expected.

**Comment by Yonjuni** [comment]
@tobiasneidig Thanks for the comment, there must have been an update regarding the camera in Android 6. In older versions there are no problems with our test devices.

**Comment by Yonjuni** [comment]
The problem originates from the permission request which for some reasons is not send.
A temporary workaround is the following: Open the `settings` of your devices, then choose `apps`, find the `QR Scanner` in the list. There under `permissions` the `camera permission` has to be granted. After done so, the scanner works fine.

**Comment by Yonjuni** [comment]
Closed by https://github.com/SecUSo/privacy-friendly-qr-scanner/commit/0109f506b6049c06ef3a8ed7ee6910d84390eb6e will be fixed in version 1.6.1

**Comment by tobiasneidig** [comment]
Thanks for the update, the app now asks for camera permission of not granted yet. After accepting the request I have to click the start Scan button again. This might be an unwanted and unexpected behavior - in my opinion the scan has to start as soon as the user accepts the request.

**Comment by Yonjuni** [comment]
@tobiasneidig I know, but there will be an update soon. We will remove the scan button completely. Thus, the app will start in the scan fragment and that was the reason we just included the permission request.
