### ISSUE TITLE
Dark theme missing

### ISSUE THREAD

**Issue by jahway603** [SecUSo/privacy-friendly-qr-scanner#182]
For visual assessibility, a dark theme is missing from this app.

**Comment by TPS** [comment]
This was merged in https://github.com/SecUSo/privacy-friendly-qr-scanner/pull/174 & since has been released.

@jahway603 Close FTW?

**Comment by jahway603** [comment]
@TPS I did not see that PR #174 existed and that it fixed Issue https://github.com/SecUSo/privacy-friendly-qr-scanner/issues/153, so I will close this issue as this app does have a Dark Theme option.
