### ISSUE TITLE
only dark screen shown after starting scan

### ISSUE THREAD

**Issue by frief** [SecUSo/privacy-friendly-qr-scanner#2]
only a dark screen is shown after starting scan. Switching on off the torch with volume keys is fine. The screen is completely dark (not only an inner area) but the back button is still functional.

I installed the scanner from f-droid on an Xperia Z1 compact running cm-12.1-20151230-NIGHTLY-amami.zip without Google apps.

[logcat_and_device_info.zip](https://github.com/SecUSo/privacy-friendly-qr-scanner/files/77104/logcat_and_device_info.zip)

Thanks for the Privacy Friendly QR-Code Scanner!

**Comment by Yonjuni** [comment]
Hey, have you tried if it works after waiting a few seconds? I'm using almost the same setup but another smartphone. Do you use XPrivacy?

**Comment by frief** [comment]
Hi Yonjuni, yes it works. It decodes QR code without having to wait (feels prompt), but as the screen is dark I cannot see the active area nor whether it's active at all.
(Not using XPrivacy)

**Comment by travisfw** [comment]
I'm having a similar issue. Black screen with a notification that I may need to restart the device, but a restart does not fix the issue.

Screen shot:
http://imgur.com/uCsEEv0

LG G3 Android 6.0
QR Scanner version 1.5 posted to F-Droid 2016 Nov 11.

**Comment by Yonjuni** [comment]
The problem seems to occur on some device - os combinations. 
There soon will be a bigger update which is targeted to fix this.

**Comment by Yonjuni** [comment]
https://github.com/SecUSo/privacy-friendly-qr-scanner/issues/16
