### ISSUE TITLE
Missing info about how-to back up this app's data

### ISSUE THREAD

**Issue by jahway603** [SecUSo/privacy-friendly-qr-scanner#200]
Missing info about how-to back up this app's data, which has been added in PR https://github.com/SecUSo/privacy-friendly-qr-scanner/pull/199 to make it clear to users how they can do this. This is very necessary when a user is switching physical phones.

**Comment by jahway603** [comment]
Resolved by PR https://github.com/SecUSo/privacy-friendly-qr-scanner/pull/199

**Comment by udenr** [comment]
Thank you for the suggestion. That's a good idea to mention the backup functionality in the readme. We should ideally do the same in the app. I have created a separate issue #204 for this.

**Comment by jahway603** [comment]
That's a good idea to include this information within the app.
