### ISSUE TITLE
Add information about backup functionality to in app FAQ.

### ISSUE THREAD

**Issue by udenr** [SecUSo/privacy-friendly-qr-scanner#204]
Add information about the backup functionality to the app's faq.
Example for `strings.xml`:
```
<string name="help_data_backup_heading">Is there a way to backup my data?</string>
<string name="help_data_backup_description">Yes. You can use the Privacy Friendly Backup app to backup and restore this application's data. In this way, the data can also be transferred to another device.</string>
```

**Comment by jahway603** [comment]
Resolved by PR https://github.com/SecUSo/privacy-friendly-qr-scanner/pull/230

**Comment by jahway603** [comment]
@udenr Should this issue be closed as PR https://github.com/SecUSo/privacy-friendly-qr-scanner/pull/230 resolved this?
