### ISSUE TITLE
Switching on/off of checking message in settings

### ISSUE THREAD

**Issue by Primokorn** [SecUSo/privacy-friendly-qr-scanner#23]
Hi,
After scanning a QR code I don't always need to check the link before opening it in my browser.
Most of QR codes I use are generated by myself, like a copy/paste from my PC to my phone.

Could you add an option to be able to remove this security screen?
Thank you.

**Comment by cbiere** [comment]
https://github.com/wewewe718/QrAndBarcodeScanner implements this.

**Comment by Kamuno** [comment]
we will not implement a option to turn this off for now but we have plans to include a better way to check the link in the future that will make this obsolete

**Comment by DanH42** [comment]
Are you able to share any details about what this planned feature is? I'm in the same position; this is the nicest overall QR scanner I've found that's open source, but this extra step to check a box for every link is incredibly annoying (and honestly feels a bit insulting).

And in the meantime, would you consider a PR that added a setting for this until a better replacement becomes available? I haven't written code for Android in a few years, but I've been considering dipping a toe back in just to make this change for myself.

**Comment by haarp** [comment]
Also curious about this. It's quite annoying having to check that box, because it's otherwise a very nice app.
