### ISSUE TITLE
App crashes on online tickets from bahn.de

### ISSUE THREAD

**Issue by jepode** [SecUSo/privacy-friendly-qr-scanner#233]
Hello,
While testing whether the app supports the code of Online tickets of bahn.de I encountered several crashes. That means the closed itself unexpectedly.
Just before closing itself, the app showed some alphanumeric characters on the lower part of the screen (probably the data it seemed to have decoded)
Version 4.6.0 from fdroid.
Google Pixel 5.
Android 14 (UP1A.231105.001.B2)

**Comment by olafhering** [comment]
backtrace from a VGN MobiCard QR code.

[vgn-mobicard.txt](https://github.com/SecUSo/privacy-friendly-qr-scanner/files/15213140/vgn-mobicard.txt)
