### ISSUE TITLE
Crash when scanning micro qr codes

### ISSUE THREAD

**Issue by udenr** [SecUSo/privacy-friendly-qr-scanner#238]
We received a report, that the app might crash when scanning micro qr codes

**Comment by udenr** [comment]
@tomjschwanke Thank you for providing an example. The problem with this aztec code should be fixed in the next update.

I'll leave this issue open as the initial reports were about micro qr codes.

**Comment by tarcisiooliveira** [comment]
Fixed with the actual update.

**Comment by udenr** [comment]
I'll close this issue then, as we have not received any new crash reports.
