### ISSUE TITLE
Product code online lookup searches in addressbook

### ISSUE THREAD

**Issue by fungs** [SecUSo/privacy-friendly-qr-scanner#25]
On my phone with Android 7.1, when I scan an EAN code and click search online, it will do the search in the local address book. IMO it would be best to define searches via an URL with a variable for the code. This way, one could configure a lookup with any service.

**Comment by Spielmops** [comment]
On my phone with Android 5: If there ist a product-code and I want to search for it online the app asks, with wich app to search. In the respectiv screen there is nearly every app of my phone (addressbook too), which I can chose, but not Firefox ....

Spielmops

**Comment by Yonjuni** [comment]
Connection to https://github.com/SecUSo/privacy-friendly-qr-scanner/issues/27

**Comment by mueller-ma** [comment]
I agree with @fungs. The best way would be to open a search machine with the code as search term, as long as the website is configurable (and not google by default :) )

**Comment by Kamuno** [comment]
This was reworked in v2.0 so that the Intents should now have the correct actions assigned. This means the correct Apps should be opened.
