### ISSUE TITLE
Copy text to clipboard

### ISSUE THREAD

**Issue by notramo** [SecUSo/privacy-friendly-qr-scanner#28]
Please add a button. (when plain text is recognised.)

**Comment by punkrock** [comment]
I just wanted to request the same. Can't wait for it. Keep up the privacy-friendly work!

**Comment by ao2** [comment]
I was also going to ask about that but then I found out that it's already possible to copy to the clipboard with 1.6.1

There are at least two ways to copy the decoded string to the clipboard:
1. long press on the saved entry in the "*History*" view.
2. long press on the text itself at the "*Back/Proceed*" screen, and then pressing the "*copy*" button which shows up at the top right.

This is with an old android 4.3

Ciao,
   Antonio

**Comment by Yonjuni** [comment]
It's possible, but very hidden.
