### ISSUE TITLE
Cant copy WLAN key

### ISSUE THREAD

**Issue by Tuffiglig** [SecUSo/privacy-friendly-qr-scanner#3]
Hallo and thank you for the app.
I scanned the Wifi QR Codes which was generated by my Router (Fritzbox 7490).
My problem is: It is only possible to copy the SSID, but I want to copy the Passwort or chose by myself what to copy.
It would be greate if you could add this to the Application.

**Comment by Yonjuni** [comment]
@Tuffiglig Does the code contain the password?

**Comment by Tuffiglig** [comment]
Hallo and thanks for your answer.
Using another Application, gives me this Information out of the QR Code:

Netzwerk-Name: xxx
Typ: WPA
Passwort: xxx

**Comment by Kamuno** [comment]
This should now be possible in v2.0
