### ISSUE TITLE
Better Workflow

### ISSUE THREAD

**Issue by natrius** [SecUSo/privacy-friendly-qr-scanner#30]
Hello, 

at first, thanks for the app, and all the ptivacy-friendly apps :)

Anyway, there are be some suggestions because the scan itself works fast, but unfortunately it has some flaws with the workflow.
After scanning its not clear what is possible to do, it seems its just for onlinesearch.
Right now its as followed:
When succesfully scanned, there is a whole new page with "Abort and don't safe" and "Proceed & safe", with "proceed" it opens a popup with "Search Online" and "Do nothing, just safe" and when pressing "Do nothing, just safe" it seriously does nothing. Its not clear where its saved. 
It can be found in the history where its possible to save a single line to the clipboard, even when somehow marked more than one. 

Unfortunately i'm no programmer, so i can just suggest improvements.
**Used Version:**
1.6.1 from F-Droid
**Android:**
7.1.2

So my suggestions:

**Options:** 
- "Immediately open Scanner instead or the "welcome screen". I mean, i opened the app, i want to scan.
- Default location for batch scan
- Default filetype for export

**Workflow:** After the Scan, just a Popup (not a complete new screen) with following possiblities: 

- Search online (Opens browser)
- Copy to Clipboard [and close QR Scanner - as option maybe?]
- Share (Email, Signal, Kontalk, Nextcloud, ...)
- Batch Scan (Just closes the popup so its possible to immediately scan the next code)
- [If Batchscan started before] End Batchscan and export (Open next dialogue with fileformat and folder)

Some of this is somewhat mentioned already in other Issues as https://github.com/SecUSo/privacy-friendly-qr-scanner/issues/28 for example.

Greetings

**Comment by Yonjuni** [comment]
@natrius Thanks for the suggestions.

> "Immediately open Scanner instead or the "welcome screen". I mean, i opened the app, i want to scan.
This is already part of version 1.7 (not released yet)
   
> Default location for batch scan
For a better overview I've opened a seperate issue: https://github.com/SecUSo/privacy-friendly-qr-scanner/issues/31

> Default filetype for export
What do you mean by that? What is exported?

> Workflow: After the Scan, just a Popup (not a complete new screen) with following possiblities:
> 
>     Search online (Opens browser)
>     Copy to Clipboard [and close QR Scanner - as option maybe?]
>     Share (Email, Signal, Kontalk, Nextcloud, ...)
>     Batch Scan (Just closes the popup so its possible to immediately scan the next code)
>     [If Batchscan started before] End Batchscan and export (Open next dialogue with fileformat and folder)

We're currently working on version 2.0 which will have another workflow and an integration of all available QR-Code tags.

**Comment by natrius** [comment]
Sorry about the confusing about the export :D
I will explain in the other topic because its related.

Thanks for the rest :)

**Comment by Yonjuni** [comment]
Thanks, I'll close this for a better overview.
