### ISSUE TITLE
Support inverted qr-codes

### ISSUE THREAD

**Issue by ao2** [SecUSo/privacy-friendly-qr-scanner#36]
The app does not recognize inverted qr-codes: those with light foreground color on a dark background.

There is a discussion open about this in the zxing issue tracker, at https://github.com/zxing/zxing/issues/194

Some apps solved the issue by processing the frame twice themselves, like https://github.com/dm77/barcodescanner/pull/265 or https://github.com/freeotp/freeotp-android/pull/192

But I think the library should provide this option itself.

Ciao,
   Antonio

**Comment by Kamuno** [comment]
Thank you for pointing this out. However, we will not include this fix ourselfes. We will update to the newest zxing version is they choose to fix this.

**Comment by ao2** [comment]
Totally understandable, thanks for the reply.

**Comment by Kamuno** [comment]
If I understand is correctly this should be fixed. We will need to take a look again.

**Comment by Kamuno** [comment]
Fixed via 1144caa09a9f2c7afd9401df1086d202a1b76bdf
