### ISSUE TITLE
external SD install location

### ISSUE THREAD

**Issue by wesinator** [SecUSo/privacy-friendly-qr-scanner#38]
Add [`installLocation` attribute](https://developer.android.com/guide/topics/data/install-location) so app can be installed/moved to external storage.

**Comment by derEisbaerX** [comment]
Fixed by  #41?

https://github.com/SecUSo/privacy-friendly-qr-scanner/blame/master/app/src/main/AndroidManifest.xml

**Comment by Kamuno** [comment]
Indeed, thank you.
Fixed via #41
