### ISSUE TITLE
[Feature Request]: geo QR-code opens Navigation App's 

### ISSUE THREAD

**Issue by 90Dragon** [SecUSo/privacy-friendly-qr-scanner#39]
If i create a QR code with following String: "geo: 51.311109,9.490041,400" the app privacy-friendly-qr-scanner has the option to search online and you can choose a browser that is installed on your device.
It would be great if in this case it has the option to open a navigation app.
Most other apps have this feature, but have the downside of overboarding permissions. I would be more than happy if you could add this feature.

You can create your own geo QR-Codes on following page:
http://goqr.me/de/#t=geolocation

Best Regards
90Dragon

**Comment by derEisbaerX** [comment]
The qr reader somehow doesn't recognize the qr codes generated with http://goqr.me/de/#t=geolocation. However if you encode your String as text AND remove the whitespaces the scanner will recognize the String as location data and offer the features you asked for.

The library used at the backend doesn't support whitespaces:
https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/client/result/GeoResultParser.java

**Comment by Kamuno** [comment]
This is already fixed in the current version. Scanning a geo qr code lets you open navigation apps.
