### ISSUE TITLE
[Feature request] copy scan result

### ISSUE THREAD

**Issue by Diapolo** [SecUSo/privacy-friendly-qr-scanner#4]
It would be nice, to be able to copy the scan result directly or from history to the clipboard. Using version 1.5 from F-Droid store here.

Edit: Thanks for the app, it a nice one and I'm looking forward for further fixes/updates :)!

**Comment by tobimensch** [comment]
I second this feature request. It looks like you can't even manually copy and paste the text at the moment.

**Comment by natrius** [comment]
This could be closed as there are now 3 Issues with the same request. FYI its possibe to paste one result after another via the history. Just in case you still need it. Its also possible to long-hold the text in the result-screen after the scan itself. Where the data is written.

**Comment by Kamuno** [comment]
It is now possible to copy the scan result via a button in the action bar. However there seems to be a bug that sets the text to null when accessing the history.
