### ISSUE TITLE
URL QR generation fails when prefixed with `http(s)://`

### ISSUE THREAD

**Issue by robsmith11** [SecUSo/privacy-friendly-qr-scanner#51]
`http://www.google.com` and `https://www.google.com` fail to generate a QR image (no error is shown, just a blank page).  `www.google.com` works fine.

Normally when one copies a URL from a browser, the `http(s)://`` prefix is included, so it would be good to support that input.

**Comment by Kamuno** [comment]
Thank you for the report.. we are in the process of fixing this along side some other problems.
