### ISSUE TITLE
App crashes when scanning QR code with vcard

### ISSUE THREAD

**Issue by mes85** [SecUSo/privacy-friendly-qr-scanner#53]
The app crashes when I scan a QR code with a (valid) vcard. The vcard info is shown after the scan for a moment, before the crash message from Android appears.
I installed the app from Google Play Store and have the latest version installed. I am using Android 9 on a Nokia 6.1 with the latest updates available from Nokia.

**Comment by Kamuno** [comment]
Thank you for the report. Would it be possible for you to post the text of the QR-Code (just overwrite any personal info with "xxxxx" or something) so we can see what excactly makes the App crash?

It seems to be a problem with Android 9 specifically as crashes only seem to happen on this version (according to the developer console).

We will take a look at it.

**Comment by mes85** [comment]
```
BEGIN:VCARD
VERSION:3.0
TEL;TYPE=work:0711 90050-NNNN
TEL;TYPE=fax:0711 90050-NNNNN
EMAIL;TYPE=work:Xxxxxx.Xxxxx@psd-rns.de
TITLE:Finanzplanerin
URL:www.psd-rheinneckarsaar.de
N:;Xxxxxx Xxxxx;;;
FN:Xxxxxx Xxxxx
ADR:;;Deckerstraße 37-39;;;70372 Stuttgart;
ORG:PSD Bank RheinNeckarSaar eG
PRODID:ez-vcard 0.8.4
END:VCARD
```

**Comment by Kamuno** [comment]
I was able to reproduce this issue. Thank you. I will take a look at it.

**Comment by asdofindia** [comment]
cv.debs.io has a qr code which reproduces the same problem on Android 9 in my device.

**Comment by quarkdown** [comment]
I can reproduce this in Android 8 and Android 10.
