### ISSUE TITLE
Scan after scan doesn't work

### ISSUE THREAD

**Issue by andbenn** [SecUSo/privacy-friendly-qr-scanner#64]
V 3.0.1 Android from Google Play

I expect to be able to scan and scan and scan codes in a relative quickly manner.  I find that I can only scan once without quitting the app or viewing the History.  Steps follow.

1. Open QR Scanner
2. Scan a bar code (UPC kind)
3. Tap Proceed (does nothing)
4. Back arrow
5. Unable to scan any other codes
6. Menu, History
7. Back arrow
8. Able to scan 1 UPC code
9. Goto step 3

One would be able to quit the app after step 5 and be functional for a single scan by going to step 1.

**Comment by Code7R** [comment]
Please fix this, it really sucks big times. Happened quite often to me. Typical repro: you use QR-Scanner, you copy the result to clipboard, use Home- or History button to go to some other app and paste. And then QR-Scanner is minimized. Next time you open it, it is still in the "results processing" screen, and pushing Back is the obvious choice, and then it does not work. It's kinda blind. Camera focuses on the QR and it's pretty sharp and contrasty but the App simply fails to recognize it.

**Comment by Kamuno** [comment]
Consecutive scans actually do work if you tap the screen once when back on the scanner view. So it seems the view just looses focus? Maybe we just need to call whatever happens in onClick in onResume.
