### ISSUE TITLE
disable beep on scan - not working

### ISSUE THREAD

**Issue by supervisitor** [SecUSo/privacy-friendly-qr-scanner#69]
version 3.0.3 from f-droid on android 6 (motorola surnia)

I disable-enable-disable it at preferences, reload/start the app on different ways (including system reboot!)... I still have this beep after scan

**Comment by bughunter2** [comment]
Can confirm. The beep always happens, regardless of the setting.

**Comment by Kamuno** [comment]
Closed via #85 9967a367f1218f31d417179cf243f1dc15bf2b67
