### ISSUE TITLE
Scanning a VCard causes strange explanation

### ISSUE THREAD

**Issue by Yonjuni** [SecUSo/privacy-friendly-qr-scanner#7]
German submission: Ich habe gerade meine VCARD gescannt  da steht dann unter der Erklärung das es eine VCARD ist TextView?

**Comment by Yonjuni** [comment]
I have just reproduced this error with this website. https://www.the-qrcode-generator.com/ 
In case a vcard is scanned, the result page shows that the type is TEXTVIEW.

**Comment by Kamuno** [comment]
Reworked in v2.0
