### ISSUE TITLE
en-/dis-able history - no differences???

### ISSUE THREAD

**Issue by supervisitor** [SecUSo/privacy-friendly-qr-scanner#70]
version 3.0.3 from f-droid on android 6 (motorola surnia)

what's the differences between history on/off?

I expected:
- off - it will not save the history always, but I can  manually touch the save button
- on - all the scans will save automatically, always
... but for me there is nothing different, I have to save a scan always manually.

**Comment by Kamuno** [comment]
See 4ebb65be3b506db2a3819cfae5f6570f0e63f0f2
