### ISSUE TITLE
Build fails with newer version of glide

### ISSUE THREAD

**Issue by htes9** [SecUSo/privacy-friendly-qr-scanner#73]
![unknown](https://user-images.githubusercontent.com/7214961/78268828-0f4bc200-7509-11ea-8d31-cf3a786c5cdf.png)

Despite if we update Zxing, and junit, build is still done, "have to check about functionality", 

``Executing tasks: [:app:assembleRelease] in project C:\Users\Bil\Desktop\privacy-friendly-qr-scanner-master

> Task :app:preBuild UP-TO-DATE
> Task :app:preReleaseBuild UP-TO-DATE
> Task :app:compileReleaseAidl NO-SOURCE
> Task :app:checkReleaseManifest UP-TO-DATE
> Task :app:generateReleaseBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:prepareLintJarForPublish UP-TO-DATE
> Task :app:dataBindingExportFeaturePackageIdsRelease UP-TO-DATE
> Task :app:compileReleaseRenderscript NO-SOURCE
> Task :app:generateReleaseSources UP-TO-DATE
> Task :app:dataBindingExportBuildInfoRelease UP-TO-DATE
> Task :app:dataBindingMergeGenClassesRelease UP-TO-DATE
> Task :app:dataBindingMergeDependencyArtifactsRelease UP-TO-DATE
> Task :app:generateReleaseResValues UP-TO-DATE
> Task :app:generateReleaseResources UP-TO-DATE
> Task :app:javaPreCompileRelease UP-TO-DATE
> Task :app:mergeReleaseResources UP-TO-DATE
> Task :app:dataBindingGenBaseClassesRelease UP-TO-DATE
> Task :app:mainApkListPersistenceRelease UP-TO-DATE
> Task :app:createReleaseCompatibleScreenManifests UP-TO-DATE
> Task :app:processReleaseManifest UP-TO-DATE
> Task :app:processReleaseResources UP-TO-DATE
> Task :app:compileReleaseJavaWithJavac UP-TO-DATE
> Task :app:compileReleaseSources UP-TO-DATE

> Task :app:lintVitalRelease
C:\Users\Bil\Desktop\privacy-friendly-qr-scanner-master\app\src\main\res\layout\fragment_result_mms.xml:12: Error: The id "btnCancel" is not defined anywhere. [UnknownId]
        android:layout_above="@+id/btnCancel"
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "UnknownId":
   The @+id/ syntax refers to an existing id, or creates a new one if it has
   not already been defined elsewhere. However, this means that if you have a
   typo in your reference, or if the referred view no longer exists, you do
   not get a warning since the id will be created on demand. This check
   catches errors where you have renamed an id without updating all of the
   references to it.

C:\Users\Bil\Desktop\privacy-friendly-qr-scanner-master\app\src\main\res\layout\activity_wifi_gnr.xml:25: Error: @+id/imageView is not a sibling in the same RelativeLayout [NotSibling]
        android:layout_toRightOf="@+id/imageView"
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\Bil\Desktop\privacy-friendly-qr-scanner-master\app\src\main\res\layout\fragment_result_wifi.xml:14: Error: @+id/btnProceed is not a sibling in the same RelativeLayout [NotSibling]
        android:layout_alignRight="@+id/btnProceed"
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   Explanation for issues of type "NotSibling":
   Layout constraints in a given ConstraintLayout or RelativeLayout should
   reference other views within the same relative layout (but not itself!)

3 errors, 0 warnings

> Task :app:checkReleaseDuplicateClasses UP-TO-DATE
> Task :app:transformClassesWithDexBuilderForRelease UP-TO-DATE
> Task :app:desugarReleaseFileDependencies UP-TO-DATE
> Task :app:mergeExtDexRelease UP-TO-DATE
> Task :app:mergeDexRelease UP-TO-DATE
> Task :app:mergeReleaseShaders UP-TO-DATE
> Task :app:compileReleaseShaders UP-TO-DATE
> Task :app:generateReleaseAssets UP-TO-DATE
> Task :app:processReleaseJavaRes NO-SOURCE
> Task :app:mergeReleaseAssets UP-TO-DATE
> Task :app:mergeReleaseJavaResource UP-TO-DATE
> Task :app:validateSigningRelease UP-TO-DATE
> Task :app:signingConfigWriterRelease UP-TO-DATE
> Task :app:mergeReleaseJniLibFolders UP-TO-DATE
> Task :app:mergeReleaseNativeLibs UP-TO-DATE
> Task :app:stripReleaseDebugSymbols UP-TO-DATE
> Task :app:packageRelease UP-TO-DATE
> Task :app:assembleRelease

BUILD SUCCESSFUL in 3s
33 actionable tasks: 1 executed, 32 up-to-date
``
Updating the latest version of glide fails to build, with following output:

![unknown2](https://user-images.githubusercontent.com/7214961/78269277-ad3f8c80-7509-11ea-8a8f-a9f988ada3f9.png)

``Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:11:5-118:19 to override.
``

**Comment by Kamuno** [comment]
Just change the libraries to androix and it should work?

**Comment by Kamuno** [comment]
Just tested this and it does indeed work. I'm gonna close this issue.. just reopen it if the problem persists for you.

**Comment by htes9** [comment]
Indeed, I tried again, it only requires complete Migration to AndroidX.
