### ISSUE TITLE
QR Scanner doesn't show up as QR Scanner when using Yubico Authenticator

### ISSUE THREAD

**Issue by Toasted-Meat** [SecUSo/privacy-friendly-qr-scanner#81]
I'm trying to scan a QR code to setup 2FA on a account and Yubico Authenticator says "No QR Code Reader Available".

I definitely have SecUSo / privacy-friendly-qr-scanner installed properly.

**Comment by derEisbaerX** [comment]
@Toasted-Meat Could you give us more information how to reproduce the error?
I tried to reproduce the error, but failed:
1. Install Yubico Authenticator
2. Press "+"-Button and select "Scan qr-code"
3.??? There is no selection menu popping up to choose a qr scanner. Instead the app asks for camera permissions and opens an internal qr scanner implementation. At least it seems to me like it.

Your android version would also be helpful.

**Comment by Kamuno** [comment]
It's on our roadmap for the future

**Comment by Kamuno** [comment]
yubico idd has an internal scanner
