### ISSUE TITLE
Text overlapping in ResultFragment

### ISSUE THREAD

**Issue by kaiserls** [SecUSo/privacy-friendly-qr-scanner#94]
The text in the sms result fragment is overlapping.
Steps to reproduce:
1. go to https://www.qr-code-generator.com/
2. use sms encoding
3. scan with app

Hints:
Sms ResultFragment isn't using "RecyclerView"

**Comment by Kamuno** [comment]
Can you add a screenshot? These overlapping texts are highly dependant on screen size and density. It would be great if you could add this info as well.

**Comment by Kamuno** [comment]
we reworked the result fragments.. If the issue persists - please reopen the issue
